# Generated by Django 5.2.1 on 2025-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_kmpinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmpinteraction',
            name='matched_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
